### PR TITLE
docs: README conform to GitHub flavored markdown

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by 5F43CCDF** [comment]
@kristapsk @AdamISZ Can this be merged?

**Comment by kristapsk** [comment]
Change itself looks good to me! Although I'm not sure what is the status of tailsjoin itself.

**Comment by AdamISZ** [comment]
> Change itself looks good to me! Although I'm not sure what is the status of tailsjoin itself.

The project is definitely dormant, I'd be amazed if it still worked, so I feel like we should mark it as "archived" and it can always be picked up again and updated if someone's interested.

**Comment by AdamISZ** [comment]
So @kristapsk I agree, merge this change and then add another change that puts a large heavy title at the top of the README saying that the project has not been updated since 2016 and therefore not useable.

**Pull request merged**
